apiVersion: v2
name: clinicore
description: Clinicore B2B clinical decision-support platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - healthcare
  - clinical-ai
  - india
maintainers:
  - name: Clinicore Platform Team
dependencies:
  - name: postgresql
    version: "~15.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "~19.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
