apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: clinicore

patches:
  # Prod: 3 replicas for application tier
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: clinicore-backend

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: relaymed-backend

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
    target:
      kind: Deployment
      name: celery-worker

images:
  - name: clinicore-backend
    newTag: "{{ .Values.imageTag }}"
  - name: relaymed-backend
    newTag: "{{ .Values.imageTag }}"

commonLabels:
  environment: prod
