apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clinicore-deployment.yaml
  - relaymed-deployment.yaml
  - celery-deployment.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - namespace.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: clinicore-platform
