apiVersion: v1
kind: Namespace
metadata:
  name: clinicore
  labels:
    app.kubernetes.io/part-of: clinicore-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
